-- MySQL Script generated by MySQL Workbench
-- vie 11 sep 2015 12:20:52 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema StockTransporteLogistica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StockTransporteLogistica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StockTransporteLogistica` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `StockTransporteLogistica` ;

-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`TipoStageArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`tipostagearea` (
  `idTipoStageArea` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoStageArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StageArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stagearea` (
  `idStageArea` INT NOT NULL AUTO_INCREMENT,
  `TipoStageArea_idTipoStageArea` INT NOT NULL,
  PRIMARY KEY (`idStageArea`, `TipoStageArea_idTipoStageArea`),
  INDEX `fk_StageArea_TipoStageArea_idx` (`TipoStageArea_idTipoStageArea` ASC),
  CONSTRAINT `fk_StageArea_TipoStageArea`
    FOREIGN KEY (`TipoStageArea_idTipoStageArea`)
    REFERENCES `StockTransporteLogistica`.`tipostagearea` (`idTipoStageArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`DarsenaEstado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`darsenaestado` (
  `idDarsenaEstado` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDarsenaEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Darsena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`darsena` (
  `idDarsena` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(80) NULL,
  `DarsenaEstado_idDarsenaEstado` INT NOT NULL,
  PRIMARY KEY (`idDarsena`, `DarsenaEstado_idDarsenaEstado`),
  INDEX `fk_Darsena_DarsenaEstado1_idx` (`DarsenaEstado_idDarsenaEstado` ASC),
  CONSTRAINT `fk_Darsena_DarsenaEstado1`
    FOREIGN KEY (`DarsenaEstado_idDarsenaEstado`)
    REFERENCES `StockTransporteLogistica`.`darsenaestado` (`idDarsenaEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`EstanteEstado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`estanteestado` (
  `idEstanteEstado` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstanteEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`estante` (
  `idEstante` INT NOT NULL AUTO_INCREMENT,
  `Fila` VARCHAR(45) NOT NULL,
  `Columna` VARCHAR(45) NOT NULL,
  `EstanteEstado_idEstanteEstado` INT NOT NULL,
  PRIMARY KEY (`idEstante`, `EstanteEstado_idEstanteEstado`),
  INDEX `fk_Estante_EstanteEstado1_idx` (`EstanteEstado_idEstanteEstado` ASC),
  CONSTRAINT `fk_Estante_EstanteEstado1`
    FOREIGN KEY (`EstanteEstado_idEstanteEstado`)
    REFERENCES `StockTransporteLogistica`.`estanteestado` (`idEstanteEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`TipoCaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`tipocaja` (
  `idTipoCaja` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoCaja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`caja` (
  `idCaja` INT NOT NULL AUTO_INCREMENT,
  `Peso` INT NOT NULL,
  `Volumen` INT NOT NULL,
  `TipoCaja_idTipoCaja` INT NOT NULL,
  PRIMARY KEY (`idCaja`, `TipoCaja_idTipoCaja`),
  INDEX `fk_Caja_TipoCaja1_idx` (`TipoCaja_idTipoCaja` ASC),
  CONSTRAINT `fk_Caja_TipoCaja1`
    FOREIGN KEY (`TipoCaja_idTipoCaja`)
    REFERENCES `StockTransporteLogistica`.`tipocaja` (`idTipoCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Pallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`pallet` (
  `idPallet` INT NOT NULL AUTO_INCREMENT,
  `cantCajas` INT NULL,
  `Peso` INT NULL,
  `Volumen` INT NULL,
  PRIMARY KEY (`idPallet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`TIpoTransporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`tipotransporte` (
  `idTIpoTransporte` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTIpoTransporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`TipoRRHH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`tiporrhh` (
  `idTipoRRHH` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoRRHH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`RRHH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`rrhh` (
  `idRRHH` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Salario` DECIMAL(10,2) NOT NULL,
  `Jefe` INT NULL,
  `TipoRRHH_idTipoRRHH` INT NOT NULL,
  PRIMARY KEY (`idRRHH`, `TipoRRHH_idTipoRRHH`),
  INDEX `fk_RRHH_TipoRRHH1_idx` (`TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_RRHH_TipoRRHH1`
    FOREIGN KEY (`TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`tiporrhh` (`idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`transporte` (
  `idTransporte` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(45) NOT NULL,
  `Peso` INT NOT NULL,
  `TIpoTransporte_idTIpoTransporte` INT NOT NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  PRIMARY KEY (`idTransporte`, `TIpoTransporte_idTIpoTransporte`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`),
  INDEX `fk_Transporte_TIpoTransporte1_idx` (`TIpoTransporte_idTIpoTransporte` ASC),
  INDEX `fk_Transporte_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_Transporte_TIpoTransporte1`
    FOREIGN KEY (`TIpoTransporte_idTIpoTransporte`)
    REFERENCES `StockTransporteLogistica`.`tipotransporte` (`idTIpoTransporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transporte_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`MotivoTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`motivoticket` (
  `idMotivoTicket` INT NOT NULL AUTO_INCREMENT,
  `Motivo` VARCHAR(45) NULL,
  PRIMARY KEY (`idMotivoTicket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(80) NULL,
  `MotivoTicket_idMotivoTicket` INT NOT NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Transporte_idTransporte` INT NOT NULL,
  `Transporte_TIpoTransporte_idTIpoTransporte` INT NOT NULL,
  `Transporte_RRHH_idRRHH` INT NOT NULL,
  `Transporte_RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idTicket`, `MotivoTicket_idMotivoTicket`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`, `Transporte_idTransporte`, `Transporte_TIpoTransporte_idTIpoTransporte`, `Transporte_RRHH_idRRHH`, `Transporte_RRHH_TipoRRHH_idTipoRRHH`),
  INDEX `fk_Ticket_MotivoTicket1_idx` (`MotivoTicket_idMotivoTicket` ASC),
  INDEX `fk_Ticket_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  INDEX `fk_Ticket_Transporte1_idx` (`Transporte_idTransporte` ASC, `Transporte_TIpoTransporte_idTIpoTransporte` ASC, `Transporte_RRHH_idRRHH` ASC, `Transporte_RRHH_TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_Ticket_MotivoTicket1`
    FOREIGN KEY (`MotivoTicket_idMotivoTicket`)
    REFERENCES `StockTransporteLogistica`.`motivoticket` (`idMotivoTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Transporte1`
    FOREIGN KEY (`Transporte_idTransporte` , `Transporte_TIpoTransporte_idTIpoTransporte` , `Transporte_RRHH_idRRHH` , `Transporte_RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`transporte` (`idTransporte` , `TIpoTransporte_idTIpoTransporte` , `RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StockCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stockcenter` (
  `idStockCenter` INT NOT NULL AUTO_INCREMENT,
  `CantEstantes` INT NOT NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  PRIMARY KEY (`idStockCenter`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`),
  INDEX `fk_StockCenter_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_StockCenter_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StockCenter_has_StageArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stockcenter_has_stagearea` (
  `StockCenter_idStockCenter` INT NOT NULL,
  `StageArea_idStageArea` INT NOT NULL,
  `StageArea_TipoStageArea_idTipoStageArea` INT NOT NULL,
  PRIMARY KEY (`StockCenter_idStockCenter`, `StageArea_idStageArea`, `StageArea_TipoStageArea_idTipoStageArea`),
  INDEX `fk_StockCenter_has_StageArea_StockCenter1_idx` (`StockCenter_idStockCenter` ASC),
  INDEX `fk_StockCenter_has_StageArea_StageArea1_idx` (`StageArea_idStageArea` ASC, `StageArea_TipoStageArea_idTipoStageArea` ASC),
  CONSTRAINT `fk_StockCenter_has_StageArea_StockCenter1`
    FOREIGN KEY (`StockCenter_idStockCenter`)
    REFERENCES `StockTransporteLogistica`.`stockcenter` (`idStockCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockCenter_has_StageArea_StageArea1`
    FOREIGN KEY (`StageArea_idStageArea` , `StageArea_TipoStageArea_idTipoStageArea`)
    REFERENCES `StockTransporteLogistica`.`stagearea` (`idStageArea` , `TipoStageArea_idTipoStageArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StockCenter_has_Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stockcenter_has_estante` (
  `StockCenter_idStockCenter` INT NOT NULL,
  `Estante_idEstante` INT NOT NULL,
  `Estante_EstanteEstado_idEstanteEstado` INT NOT NULL,
  PRIMARY KEY (`StockCenter_idStockCenter`, `Estante_idEstante`, `Estante_EstanteEstado_idEstanteEstado`),
  INDEX `fk_StockCenter_has_Estante_StockCenter1_idx` (`StockCenter_idStockCenter` ASC),
  INDEX `fk_StockCenter_has_Estante_Estante1_idx` (`Estante_idEstante` ASC, `Estante_EstanteEstado_idEstanteEstado` ASC),
  CONSTRAINT `fk_StockCenter_has_Estante_StockCenter1`
    FOREIGN KEY (`StockCenter_idStockCenter`)
    REFERENCES `StockTransporteLogistica`.`stockcenter` (`idStockCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockCenter_has_Estante_Estante1`
    FOREIGN KEY (`Estante_idEstante` , `Estante_EstanteEstado_idEstanteEstado`)
    REFERENCES `StockTransporteLogistica`.`estante` (`idEstante` , `EstanteEstado_idEstanteEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StockCenter_has_Darsena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stockcenter_has_darsena` (
  `StockCenter_idStockCenter` INT NOT NULL,
  `Darsena_idDarsena` INT NOT NULL,
  `Darsena_DarsenaEstado_idDarsenaEstado` INT NOT NULL,
  PRIMARY KEY (`StockCenter_idStockCenter`, `Darsena_idDarsena`, `Darsena_DarsenaEstado_idDarsenaEstado`),
  INDEX `fk_StockCenter_has_Darsena_StockCenter1_idx` (`StockCenter_idStockCenter` ASC),
  INDEX `fk_StockCenter_has_Darsena_Darsena1_idx` (`Darsena_idDarsena` ASC, `Darsena_DarsenaEstado_idDarsenaEstado` ASC),
  CONSTRAINT `fk_StockCenter_has_Darsena_StockCenter1`
    FOREIGN KEY (`StockCenter_idStockCenter`)
    REFERENCES `StockTransporteLogistica`.`stockcenter` (`idStockCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockCenter_has_Darsena_Darsena1`
    FOREIGN KEY (`Darsena_idDarsena` , `Darsena_DarsenaEstado_idDarsenaEstado`)
    REFERENCES `StockTransporteLogistica`.`darsena` (`idDarsena` , `DarsenaEstado_idDarsenaEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StockCenter_has_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stockcenter_has_caja` (
  `StockCenter_idStockCenter` INT NOT NULL,
  `Caja_idCaja` INT NOT NULL,
  `Caja_TipoCaja_idTipoCaja` INT NOT NULL,
  PRIMARY KEY (`StockCenter_idStockCenter`, `Caja_idCaja`, `Caja_TipoCaja_idTipoCaja`),
  INDEX `fk_StockCenter_has_Caja_StockCenter1_idx` (`StockCenter_idStockCenter` ASC),
  INDEX `fk_StockCenter_has_Caja_Caja1_idx` (`Caja_idCaja` ASC, `Caja_TipoCaja_idTipoCaja` ASC),
  CONSTRAINT `fk_StockCenter_has_Caja_StockCenter1`
    FOREIGN KEY (`StockCenter_idStockCenter`)
    REFERENCES `StockTransporteLogistica`.`stockcenter` (`idStockCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockCenter_has_Caja_Caja1`
    FOREIGN KEY (`Caja_idCaja` , `Caja_TipoCaja_idTipoCaja`)
    REFERENCES `StockTransporteLogistica`.`caja` (`idCaja` , `TipoCaja_idTipoCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Pallet_has_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`pallet_has_caja` (
  `Pallet_idPallet` INT NOT NULL,
  `Caja_idCaja` INT NOT NULL,
  `Caja_TipoCaja_idTipoCaja` INT NOT NULL,
  PRIMARY KEY (`Pallet_idPallet`, `Caja_idCaja`, `Caja_TipoCaja_idTipoCaja`),
  INDEX `fk_Pallet_has_Caja_Pallet1_idx` (`Pallet_idPallet` ASC),
  INDEX `fk_Pallet_has_Caja_Caja1_idx` (`Caja_idCaja` ASC, `Caja_TipoCaja_idTipoCaja` ASC),
  CONSTRAINT `fk_Pallet_has_Caja_Pallet1`
    FOREIGN KEY (`Pallet_idPallet`)
    REFERENCES `StockTransporteLogistica`.`pallet` (`idPallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pallet_has_Caja_Caja1`
    FOREIGN KEY (`Caja_idCaja` , `Caja_TipoCaja_idTipoCaja`)
    REFERENCES `StockTransporteLogistica`.`caja` (`idCaja` , `TipoCaja_idTipoCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`StageArea_has_Pallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`stagearea_has_pallet` (
  `StageArea_idStageArea` INT NOT NULL,
  `StageArea_TipoStageArea_idTipoStageArea` INT NOT NULL,
  `Pallet_idPallet` INT NOT NULL,
  PRIMARY KEY (`StageArea_idStageArea`, `StageArea_TipoStageArea_idTipoStageArea`, `Pallet_idPallet`),
  INDEX `fk_StageArea_has_Pallet_StageArea1_idx` (`StageArea_idStageArea` ASC, `StageArea_TipoStageArea_idTipoStageArea` ASC),
  INDEX `fk_StageArea_has_Pallet_Pallet1_idx` (`Pallet_idPallet` ASC),
  CONSTRAINT `fk_StageArea_has_Pallet_StageArea1`
    FOREIGN KEY (`StageArea_idStageArea` , `StageArea_TipoStageArea_idTipoStageArea`)
    REFERENCES `StockTransporteLogistica`.`stagearea` (`idStageArea` , `TipoStageArea_idTipoStageArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StageArea_has_Pallet_Pallet1`
    FOREIGN KEY (`Pallet_idPallet`)
    REFERENCES `StockTransporteLogistica`.`pallet` (`idPallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Transporte_has_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`transporte_has_caja` (
  `Transporte_idTransporte` INT NOT NULL,
  `Transporte_TIpoTransporte_idTIpoTransporte` INT NOT NULL,
  `Transporte_RRHH_idRRHH` INT NOT NULL,
  `Transporte_RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Caja_idCaja` INT NOT NULL,
  `Caja_TipoCaja_idTipoCaja` INT NOT NULL,
  PRIMARY KEY (`Transporte_idTransporte`, `Transporte_TIpoTransporte_idTIpoTransporte`, `Transporte_RRHH_idRRHH`, `Transporte_RRHH_TipoRRHH_idTipoRRHH`, `Caja_idCaja`, `Caja_TipoCaja_idTipoCaja`),
  INDEX `fk_Transporte_has_Caja_Transporte1_idx` (`Transporte_idTransporte` ASC, `Transporte_TIpoTransporte_idTIpoTransporte` ASC, `Transporte_RRHH_idRRHH` ASC, `Transporte_RRHH_TipoRRHH_idTipoRRHH` ASC),
  INDEX `fk_Transporte_has_Caja_Caja1_idx` (`Caja_idCaja` ASC, `Caja_TipoCaja_idTipoCaja` ASC),
  CONSTRAINT `fk_Transporte_has_Caja_Transporte1`
    FOREIGN KEY (`Transporte_idTransporte` , `Transporte_TIpoTransporte_idTIpoTransporte` , `Transporte_RRHH_idRRHH` , `Transporte_RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`transporte` (`idTransporte` , `TIpoTransporte_idTIpoTransporte` , `RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transporte_has_Caja_Caja1`
    FOREIGN KEY (`Caja_idCaja` , `Caja_TipoCaja_idTipoCaja`)
    REFERENCES `StockTransporteLogistica`.`caja` (`idCaja` , `TipoCaja_idTipoCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Transporte_has_Pallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`transporte_has_pallet` (
  `Transporte_idTransporte` INT NOT NULL,
  `Transporte_TIpoTransporte_idTIpoTransporte` INT NOT NULL,
  `Transporte_RRHH_idRRHH` INT NOT NULL,
  `Transporte_RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Pallet_idPallet` INT NOT NULL,
  PRIMARY KEY (`Transporte_idTransporte`, `Transporte_TIpoTransporte_idTIpoTransporte`, `Transporte_RRHH_idRRHH`, `Transporte_RRHH_TipoRRHH_idTipoRRHH`, `Pallet_idPallet`),
  INDEX `fk_Transporte_has_Pallet_Transporte1_idx` (`Transporte_idTransporte` ASC, `Transporte_TIpoTransporte_idTIpoTransporte` ASC, `Transporte_RRHH_idRRHH` ASC, `Transporte_RRHH_TipoRRHH_idTipoRRHH` ASC),
  INDEX `fk_Transporte_has_Pallet_Pallet1_idx` (`Pallet_idPallet` ASC),
  CONSTRAINT `fk_Transporte_has_Pallet_Transporte1`
    FOREIGN KEY (`Transporte_idTransporte` , `Transporte_TIpoTransporte_idTIpoTransporte` , `Transporte_RRHH_idRRHH` , `Transporte_RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`transporte` (`idTransporte` , `TIpoTransporte_idTIpoTransporte` , `RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transporte_has_Pallet_Pallet1`
    FOREIGN KEY (`Pallet_idPallet`)
    REFERENCES `StockTransporteLogistica`.`pallet` (`idPallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Estante_has_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`estante_has_caja` (
  `Estante_idEstante` INT NOT NULL,
  `Estante_EstanteEstado_idEstanteEstado` INT NOT NULL,
  `Caja_idCaja` INT NOT NULL,
  `Caja_TipoCaja_idTipoCaja` INT NOT NULL,
  PRIMARY KEY (`Estante_idEstante`, `Estante_EstanteEstado_idEstanteEstado`, `Caja_idCaja`, `Caja_TipoCaja_idTipoCaja`),
  INDEX `fk_Estante_has_Caja_Caja1_idx` (`Caja_idCaja` ASC, `Caja_TipoCaja_idTipoCaja` ASC),
  INDEX `fk_Estante_has_Caja_Estante1_idx` (`Estante_idEstante` ASC, `Estante_EstanteEstado_idEstanteEstado` ASC),
  CONSTRAINT `fk_Estante_has_Caja_Estante1`
    FOREIGN KEY (`Estante_idEstante` , `Estante_EstanteEstado_idEstanteEstado`)
    REFERENCES `StockTransporteLogistica`.`estante` (`idEstante` , `EstanteEstado_idEstanteEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estante_has_Caja_Caja1`
    FOREIGN KEY (`Caja_idCaja` , `Caja_TipoCaja_idTipoCaja`)
    REFERENCES `StockTransporteLogistica`.`caja` (`idCaja` , `TipoCaja_idTipoCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Mail` VARCHAR(60) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`pedido` (
  `idPedido` INT NOT NULL,
  `cantCajas` INT NULL,
  `cantPallets` INT NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idPedido`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`, `Cliente_idCliente`),
  INDEX `fk_Pedido_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Pedido_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `StockTransporteLogistica`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `Monto` DECIMAL(10,2) NOT NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`idFactura`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`, `Cliente_idCliente`),
  INDEX `fk_Factura_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Factura_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `StockTransporteLogistica`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`HojaRuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`hojaruta` (
  `idHojaRuta` INT NOT NULL AUTO_INCREMENT,
  `Destino` VARCHAR(45) NOT NULL,
  `cantCajas` INT NOT NULL,
  `cantPallets` INT NOT NULL,
  `Transporte_idTransporte` INT NOT NULL,
  `Transporte_TIpoTransporte_idTIpoTransporte` INT NOT NULL,
  `Transporte_RRHH_idRRHH` INT NOT NULL,
  `Transporte_RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  PRIMARY KEY (`idHojaRuta`, `Transporte_idTransporte`, `Transporte_TIpoTransporte_idTIpoTransporte`, `Transporte_RRHH_idRRHH`, `Transporte_RRHH_TipoRRHH_idTipoRRHH`),
  INDEX `fk_HojaRuta_Transporte1_idx` (`Transporte_idTransporte` ASC, `Transporte_TIpoTransporte_idTIpoTransporte` ASC, `Transporte_RRHH_idRRHH` ASC, `Transporte_RRHH_TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_HojaRuta_Transporte1`
    FOREIGN KEY (`Transporte_idTransporte` , `Transporte_TIpoTransporte_idTIpoTransporte` , `Transporte_RRHH_idRRHH` , `Transporte_RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`transporte` (`idTransporte` , `TIpoTransporte_idTIpoTransporte` , `RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockTransporteLogistica`.`Autenticación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockTransporteLogistica`.`user` (
  `idAutenticacion` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Authkey` VARCHAR(250) NULL,
  `Token` VARCHAR(250) NULL,
  `RRHH_idRRHH` INT NOT NULL,
  `RRHH_TipoRRHH_idTipoRRHH` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `activate` TINYINT NOT NULL DEFAULT(0),
  PRIMARY KEY (`idAutenticacion`, `RRHH_idRRHH`, `RRHH_TipoRRHH_idTipoRRHH`),
  INDEX `fk_Autenticacion_RRHH1_idx` (`RRHH_idRRHH` ASC, `RRHH_TipoRRHH_idTipoRRHH` ASC),
  CONSTRAINT `fk_Autenticacion_RRHH1`
    FOREIGN KEY (`RRHH_idRRHH` , `RRHH_TipoRRHH_idTipoRRHH`)
    REFERENCES `StockTransporteLogistica`.`rrhh` (`idRRHH` , `TipoRRHH_idTipoRRHH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
